databases:
  - name: Villow
    databaseName: dpg-clbt3bl4lnec73dvndcg-a
    user: mlkz

services:
  - type: web
    name: Villow
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-clbt3bl4lnec73dvndcg-a
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
