databases:
  - name: Villow
    databaseName: Villow
    user: Mlkz

services:
  - type: web
    name: Villow
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Villow
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
